apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "argocd_application.fullname" . }}
  labels:
    {{- include "argocd_application.labels" . | nindent 4 }}
spec:
  {{ toYaml .Values.spec | nindent 2 }}
